In [50]:
import numpy as np

# 1.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

## 1.1 배열 생성

### 1.1.1 기본 배열 생성

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [8]:
x = np.arange(0,10)
# 엘레멘트 와일드 연산


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a = np.arange([1,2,3,4])
a[:3] = 1
a 

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [ ]:
# rank : 1~100등까지 등수가 담긴 array
# 1 ~ 20: 1
# 21 ~ 40: 2
# 41 ~ 60 : 3
# 61 ~ 80 : 4
# 81 ~ 100 : 5
# 의 값을 부여

In [11]:
ranks = np.random.choice(np.arange(1,101), size=100)

In [12]:
ranks

array([ 63,  12,  59,  80,   9,  60,  72,  39,  52,  90,  92, 100,  15,
        66,  48,  77,  48,  16,  21,  87,   6,  30,  18,  14,  82,  67,
        68,  75,  18,  36,  21,  70,  47,  66,  78,  94,  32,  21,  37,
         7,  84,  92,  84,  45,  86,  18,  90,  47,  80,  32,  48,  15,
        91,  90,  75,  68,  74,  69,  98,  57,  67,  85,  40,  14,  50,
        49,  59,  83,  79,  26,   4,  46,  74,  92,   8,  33,  79,  34,
        91,  72,  33,  90,  80,  92,  97,  18,  49,  27,   9,  70,  49,
        53,  97,  19,   8,  58,  33,  68,  85,  36])

In [ ]:
# solution
grades = []
for rank in ranks:
    if rank > 80:
        grades.append(5)
    elif rank > 60:
        grades.append(4)
    elif rank > 40:
        grades.append(3)
    elif rank > 20:
        grades.append(2)
    else:
        grades.append(1) 
grades

In [19]:
# solution2
((ranks - 1) // 20) + 1

array([4, 1, 3, 4, 1, 3, 4, 2, 3, 5, 5, 5, 1, 4, 3, 4, 3, 1, 2, 5, 1, 2,
       1, 1, 5, 4, 4, 4, 1, 2, 2, 4, 3, 4, 4, 5, 2, 2, 2, 1, 5, 5, 5, 3,
       5, 1, 5, 3, 4, 2, 3, 1, 5, 5, 4, 4, 4, 4, 5, 3, 4, 5, 2, 1, 3, 3,
       3, 5, 4, 2, 1, 3, 4, 5, 1, 2, 4, 2, 5, 4, 2, 5, 4, 5, 5, 1, 3, 2,
       1, 4, 3, 3, 5, 1, 1, 3, 2, 4, 5, 2], dtype=int32)

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [20]:
print(np.linspace(2,3, num =5))
print(np.linspace(2,3, num =5, endpoint= False))

# 등분으로 잘쪼개주니까 사용가능 하다.

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]


#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1) # 항등행렬
```

In [22]:
x = np.eye(10, k =1) # 대각선에 기준으로 마이너스면 아래방향으로 움직인다.  플러스는 윗방향으로 움직인다
x

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

In [30]:
np.ones(5, dtype = np.float32)

array([1., 1., 1., 1., 1.], dtype=float32)

#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [27]:
np.full((2,3,5),np.inf) # inf(값이 무한)

array([[[inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf]],

       [[inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf]]])

#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [31]:
np.tril(([1,2,3],[4,5,6],[7,8,9])) 
# 상단부분을 0으로 바꾸고 하단부를 원래 행렬의 값으로 찬다

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [33]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], k=-1) 

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

In [34]:
np.triu([[1,2,3],[4,5,6],[7,8,9]], k=-1) 

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9]])

### 1.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

In [40]:
np.random.random(size=(2,3))

array([[0.49193531, 0.05992046, 0.41188568],
       [0.37931148, 0.25511037, 0.81621772]])

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [46]:
np.array(random.randint(0,10,size=(5,2)), dtype = np.float32)

NameError: name 'random' is not defined

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

In [47]:
np.random.normal(0,10,size=(3,2))

array([[ -1.1043485 ,   1.03446896],
       [-12.12994837,   7.08325657],
       [-14.45402996,   2.85973771]])

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

In [54]:
x = np.random.randn(2,3)
x

array([[ 0.84099051, -1.05627952, -0.59678501],
       [ 0.21590404,  0.13788626,  2.86433326]])

In [ ]:
# 함수 만들기
# 함수의 입력은 복권 구매 금액
# 금액에 맞는 복권 매수 구매
# 복권은 자동임
# 1등번호는 6,11,16,19,21,32
# 복권 번호는 1~ 45
win_number = [6,11,16,19,21,32]

In [61]:
def buy_lottery_tickets(amount):


    num_tickets = amount // 1000
    lottery_numbers = np.random.choice(range(1, 46), size=num_tickets*6, replace=True).reshape(num_tickets, 6)
    amount = 5000 
    lottery_numbers = buy_lottery_tickets(amount)
    print("구매한 복권 매수:", lottery_numbers.shape[0])
    print("당첨 번호:", win_number)
    print("복권 번호:", lottery_numbers)

In [63]:
win_number = [6,11,16,19,21,32]
def lotto(money):
    count = 0 
    for _ in range(money // 1000):
        my_numbers = list(np.random.randint(1,46, 6))
        my_numbers.sort()
        my_numbers
        if win_number == my_numbers:
            count += 1
    return count

In [ ]:
lotto(100000000000)

## 1.2 배열 조작

### 1.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

In [72]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [69]:
np.concatenate([a, b], axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [70]:
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]])

### 1.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3)
np.split(x, [3, 5, 6, 10])
```

In [74]:
x = np.arange(9)

np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [75]:
x = np.arange(10)

np.split(x,[2,3,5,7])

[array([0, 1]), array([2]), array([3, 4]), array([5, 6]), array([7, 8, 9])]

### 1.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


In [79]:
x = np.arange(30) # x의모양을 바꿔줄떄 사용한다.

x.reshape(5,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

In [82]:
x = np.arange(36).reshape(2,2,3,3)
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

In [84]:
np.arange(10).reshape(10,1,1,1,1)
x.squeeze()

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

In [89]:
x = np.arange(10)
print(x.reshape(1,10))
x = np.expand_dims(x,0)
print(x.shape)
print(x)
print(x.squeeze().shape)

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[[0 1 2 3 4 5 6 7 8 9]]
(10,)


### 1.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [93]:
x = np.arange(10)
print(np.roll(x,1))
print(np.roll(x,-1))

[9 0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9 0]


In [95]:
x = np.arange(10).reshape(2,5)
print(x)
print('-'*30)
print(np.roll(x,1,axis=0))
print('-'*30)
print(np.roll(x,-1,axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[5 6 7 8 9]
 [0 1 2 3 4]]
------------------------------
[[1 2 3 4 0]
 [6 7 8 9 5]]


##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [98]:
x = np.arange(10).reshape(5,2)
print(x)
print('-'*15)
print(np.flip(x, axis=0))
print(x[::-1, :])
print('-'*15)
print(np.flip(x, axis=1))
print(x[:, ::-1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
---------------
[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]
[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]
---------------
[[1 0]
 [3 2]
 [5 4]
 [7 6]
 [9 8]]
[[1 0]
 [3 2]
 [5 4]
 [7 6]
 [9 8]]


### 1.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxis(0, 2)    # 0 <-> 2
```

In [103]:
# tensorflow
# pytorch
x = np.arange(20).reshape(4,5)
print(x)
print('-'*20)
print(x.swapaxes(1,0)) # 전치행렬
print('-'*20)
print(x.reshape(5,4)) 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
--------------------
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [105]:
x = np.arange(20).reshape(2,2,5)
print(x)
print('-'*20)
print(x.swapaxes(2,0)) # 전치행렬
# swapaxes 은 데이터 값도 같이바뀐다.
# reshape 은 데이터값은 변경하지않는다. 데이터를 다르게 보여주는것 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
--------------------
[[[ 0 10]
  [ 5 15]]

 [[ 1 11]
  [ 6 16]]

 [[ 2 12]
  [ 7 17]]

 [[ 3 13]
  [ 8 18]]

 [[ 4 14]
  [ 9 19]]]


#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

In [106]:
x = np.arange(100).reshape(5,2,10)
print(x.transpose(0,2,1).shape)
print(x.transpose(2,0,1).shape)
# transpose 도 데이터값이 바뀐다.

(5, 10, 2)
(10, 5, 2)


### 1.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [112]:
x = np.random.randint(0,10,(5,2))
print(x)
print('-'*20)
x.sort(axis=0)
print(x)
print('-'*20)
x.sort(axis=1)
print(x)
# sort는 데이터값이 바뀐다.

[[7 6]
 [6 6]
 [3 0]
 [5 0]
 [6 0]]
--------------------
[[3 0]
 [5 0]
 [6 0]
 [6 6]
 [7 6]]
--------------------
[[0 3]
 [0 5]
 [0 6]
 [6 6]
 [6 7]]


#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


In [113]:
x = np.random.randint(0,10,(5,2))
print(x)
print('-'*20)
print(x.argsort(axis=0))
print('-'*20)
print(x.argsort(axis=1))
# arg : 인덱스 기준이 오름차순

[[2 3]
 [7 4]
 [8 9]
 [0 2]
 [6 7]]
--------------------
[[3 3]
 [0 0]
 [4 1]
 [1 4]
 [2 2]]
--------------------
[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]


### 1.2.7 기타

##### unique

배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [117]:
x = np.array([3,4,3,3,4])
np.unique(x)

array([3, 4])

#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


In [119]:
x = np.full((3,4),np.nan)
np.nan_to_num(x, nan=-1)

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trip_zeros(x, trip='f')    # 앞의 0만 제거
np.trip_zeros(x, trip='b')    # 뒤의 0만 제거
np.trip_zeros(x, trip='fb')   # 앞뒤 0 제거
```

In [125]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
print(np.trip_zeros(x, trim='f'))    # 앞의 0만 제거
np.trip_zeros(x, trim='b')    # 뒤의 0만 제거
np.trip_zeros(x, trim='ff')   # 앞뒤 0 제거

AttributeError: module 'numpy' has no attribute 'trip_zeros'

stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [132]:
x = np.arange(10)

np.lib.stride_tricks.sliding_window_view(x,5).mean(axis=1)

array([2., 3., 4., 5., 6., 7.])

In [133]:
np.lib.stride_tricks.sliding_window_view(x,5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

## 1.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

In [ ]:
x = np.arange(6).reshape(2,3)
print(x)
print('-'*20)
print(np.argmax(x,axis=0))
print('-'*20)
print(np.argmax(x,axis=1))

### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



In [134]:
x = np.arange(6).reshape(2,3)
print(x)
print('-'*20)
print(np.argmin(x,axis=0))
print('-'*20)
print(np.argmin(x,axis=1))

[[0 1 2]
 [3 4 5]]
--------------------
[1 1 1]
--------------------
[2 2]


### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [144]:
x = np.arange(6)
x[np.where(x < 3)]

array([0, 1, 2])

In [142]:
x = np.arange(6).reshape(2,3)
print(x < 3)
print('-'*20)
print(np.where(x < 3))
print('-'*20)
print(np.where(x < 3,1,0))
# where 인덱스 번호를 불러온다.

[[ True  True  True]
 [False False False]]
--------------------
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
--------------------
[[1 1 1]
 [0 0 0]]


### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

In [145]:
x = np.random.randint(1,10,10)
print(x)
print(np.extract(x > 5 ,x)) 
# extract 인덱스 데이터 값을 뽑아낸다

[1 9 7 7 5 5 3 6 6 4]
[9 7 7 6 6]


##  1.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

inv

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

## 1.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

### min

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```